### PR TITLE
fix(#5): support disposing point clouds

### LINKED ISSUE #5: Clarify clearing of clouds from scene
I'm writing an application which allows changing of the contents of the scene, including point clouds.
This is the function which adds point clouds to the scene:
```ts
private async _addPotreeCloud(
  potree: Element_element_PotreeCloud,
): Promise<any> {
  const pco = await new PointCloud(
    potree.filename,
    potree.baseurl,
    new Vector3(
      potree.pose.scale.x,
      potree.pose.scale.y,
      potree.pose.scale.z,
    ),
  ).getpco();

  pco.position.set(
    potree.pose.position.x,
    potree.pose.position.y,
    potree.pose.position.z,
  );
  pco.userData = { id: potree.id, parentId: potree.parent.id };
  this.scene.add(pco);
}
```

When changing contents, following code is executed (initially executed with the scene) before adding anything, in order to remove everything from scene:
```ts
private _clearScene(object): void {
  while (object.children.length > 0) {
    this._clearScene(object.children[0]);
    object.remove(object.children[0]);
  }
  if (object.geometry) {
    object.geometry.dispose();
  }
  if (object.material) {
    object.material.dispose();
  }
  if (object.texture) {
    object.texture.dispose();
  }
}
```

But when making multiple changes of content, I saw in Chrome that the number of threads is rising.
See this screencast:
https://gfycat.com/SilentRecentClownanemonefish

Am I doing something wrong in `_clearScene`? Or are the web workers not properly stopped?

### PR DESCRIPTION
**Pull request by hccampos**
Fixes #5

### CODE REVIEW

File: src/materials/point-cloud-material.ts [hunk 1]
```diff
@@ -175,71 +180,42 @@ export class PointCloudMaterial extends RawShaderMaterial {
...
-  intensityGamma!: number;
-  @uniform('intensityRange')
-  intensityRange!: [number, number];
-  @uniform('maxSize')
-  maxSize!: number;
-  @uniform('minSize')
-  minSize!: number;
-  @uniform('near')
-  near!: number;
+  @uniform('far') far!: number; // prettier-ignore
```
Comment (hccampos) [inline src/materials/point-cloud-material.ts]: Prettier can't decide what to do with decorators. Meh
